[build]
  command = "(pnpm -v || npm install --global pnpm) && pnpm --workspace-root --recursive --no-frozen-lockfile install && pnpm --workspace-root run package && pnpm run build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../../packages/ui"
  publish = "build"

[build.environment]
  NPM_FLAGS = "--version"