[build]
  command = """\
    npx pnpm install --store=node_modules/.pnpm-store --workspace-root --filter ./packages &&
    npx pnpm package --store=node_modules/.pnpm-store --workspace-root --filter ./packages &&
    npx pnpm install --store=node_modules/.pnpm-store &&
    npx pnpm build --store=node_modules/.pnpm-store
    """

[build.environment]
  NPM_FLAGS = "--version"