[build]
  command = """\
    npx pnpm install --workspace-root --filter {packages}
    npx pnpm package --workspace-root --filter {packages}
    npx pnpm install
    npx pnpm build
    """

[build.environment]
  NPM_FLAGS = "--only=production"