[build]
  command = "pnpm --workspace-root --recursive install && pnpm --workspace-root --recursive run package && pnpm run build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../../packages/ui"
  publish = "build"

[build.environment]
  NPM_FLAGS = "--version"