[build]
  command = """\
    npx pnpm install --workspace-root --store=node_modules/.pnpm-store --shamefully-hoist --filter ./packages
    npx pnpm package --workspace-root --store=node_modules/.pnpm-store --filter ./packages
    npx pnpm install --store=node_modules/.pnpm-store --shamefully-hoist
    npx pnpm build --store=node_modules/.pnpm-store
    """

[build.environment]
  NPM_FLAGS = "--only=production"