[build]
  command = "npx pnpm install --filter {packages} --recursive --store=node_modules/.pnpm-store && npx pnpm package --filter {packages} --recursive && npx pnpm install --recursive --store=node_modules/.pnpm-store && npx pnpm build"

[build.environment]
  NPM_FLAGS = "--version"